### ISSUE TITLE
java 6 support

### ISSUE THREAD

**Issue by fommil** [rickynils/scalacheck#227] opened 2016-03-25 17:53 UTC
I get this sort of error when running my tests, necessarily against java 6 because that is the official JDK for scala and we (ensime-server) are in the community build.

Workaround is to revert to 1.12.5

```
[error] Uncaught exception when running org.ensime.sexp.SexpParserCheck: java.lang.IncompatibleClassChangeError: Implementing class
sbt.ForkMain$ForkError: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.ensime.sexp.SexpParserCheck.<init>(SexpParserCheck.scala:10)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
```

**Comment by rickynils** [comment] 2016-03-25 18:44
Hmm, which exact ScalaCheck version is this? As far as I can see, only the releases built for the Scala 1.12 milestones have been built with Java 8. The rest should be Java 6.

**Comment by fommil** [comment] 2016-03-25 19:08
1.13

**Comment by rickynils** [comment] 2016-03-25 19:25
Thanks, I'll look into that.

**Comment by rickynils** [comment] 2016-04-14 14:32
@fommil Could you provide instructions for reproducing this? I have tried using ScalaCheck 1.13.0 (for Scala 2.11) in a simple project, with various versions of the oracle jdk (6,7,8) and setting different jvm targets (jvm-6, jvm-7, jvm-8). I can't seem to trigger the exception you get.

**Comment by fommil** [comment] 2016-04-14 14:51
sure, just check out ensime-server and upgrade scalacheck to the latest version, then run `sbt test` (probably just `sbt s-express/test` would be enough) and you should see the exceptions.

**Comment by rickynils** [comment] 2016-04-14 17:31
This is not a java 6 problem. This is caused by ScalaTest not being compatible with ScalaCheck 1.13, which makes this issue a duplicate of #217. I'll continue discussion in that issue...

**Closed by rickynils** 2016-04-14 17:31 UTC
